version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/vite-aws
    overwrite: yes
permissions:
  - object: /var/www/html/vite-aws
    pattern: "**"
    owner: www-data
    group: www-data
    mode: 755
  - object: /var/www/html/vite-aws
    pattern: "**"
    type:
      - file
    owner: www-data
    group: www-data
    mode: 644
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
